<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_UsernameUsernamePasswordPasswordRememb_bb32a5</name>
   <tag></tag>
   <elementGuidId>fecf61a1-03f6-43c8-a1e3-f4d670728412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='#']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>1d848813-17f7-47d5-a8b8-30a82a896c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>54644983-c0a1-415b-8ce5-9b7b64f1f20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab31e8fd-7e41-4372-aa95-67cff3bd0aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernameUsernamePasswordPasswordRemember meForgot Password ?Continue</value>
      <webElementGuid>aa938bb5-2e32-4bd7-90f6-fed114760607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-65itpv&quot;]/div[@class=&quot;MuiBox-root css-1llb0e0&quot;]/div[@class=&quot;MuiBox-root css-1w6qte8&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg css-bq6go7&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiCard-root css-1708tef&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-18v1xfh&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-6 css-1cj1go5&quot;]/div[@class=&quot;MuiStack-root css-1j4eegm&quot;]/div[@class=&quot;MuiBox-root css-14n14ph&quot;]/form[1]</value>
      <webElementGuid>576bbfe5-f3a8-4551-8b74-675350d1047c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='#']</value>
      <webElementGuid>cf4452bd-568e-4956-b4b6-b8b771c3d5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div/div/div[2]/form</value>
      <webElementGuid>acc66829-2fa1-42dd-ab3f-245d64ffb083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to oli3 platform!'])[1]/following::form[1]</value>
      <webElementGuid>68744176-6bd6-4474-921f-d534bd95b5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::form[1]</value>
      <webElementGuid>31177bd0-b144-4926-b5d4-25a0668d8f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>2d4c10cc-ed7e-46f0-a18a-7b0d0f527ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'UsernameUsernamePasswordPasswordRemember meForgot Password ?Continue' or . = 'UsernameUsernamePasswordPasswordRemember meForgot Password ?Continue')]</value>
      <webElementGuid>cba3a30f-df76-49ac-9be7-07e1e8349e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
